### ISSUE TITLE
Implement Reminder System for Expiry and Low Stock

### ISSUE THREAD

**Issue by shyanyong** [AY2324S1-CS2103T-T15-2/tp#105]
Create a reminder system that alerts users when their prescriptions are close to expiry (e.g., 7 days before) or when the stock is running low (e.g., 10 left). This system should use a separate window or UI indicators for prescriptions that fit these criteria.

**Comment by ChongWeiJie29** [comment]
User stories:
As an organized patient, 
I can get a reminder when certain pills are running low/expiring
so that I know when to visit the pharmacy to restock.
