### ISSUE TITLE
Add Manual Drug Interaction Checking

### ISSUE THREAD

**Issue by shyanyong** [AY2324S1-CS2103T-T15-2/tp#107]
Introduce a feature that allows users to manually specify conflicting drugs for their prescriptions. Create an attribute in prescriptions for conflicting drugs and implement the logic to check against a list of conflicting drugs. When users add a prescription with potential conflicts, display a prompt to inform them.

**Comment by ChongWeiJie29** [comment]
User story:
As a user managing both prescription and over-the-counter medications, 
I can add all of them for a comprehensive view of my medication regimen, 
so that I can reduce the risk of drug interactions.
