### ISSUE TITLE
[PE-D][Tester A] No warning shown when adding invalid date

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T15-2/tp#177]
I tried adding an invalid date (in this case, an invalid month)

`add mn/some meds sd/22/22/2222`

And the UI did not update to show me any warnings

![image.png](https://raw.githubusercontent.com/garylow2001/ped/main/files/f62b6a54-0a79-4c19-ad90-574b00667816.png)

This is the error shown in the terminal

![image.png](https://raw.githubusercontent.com/garylow2001/ped/main/files/eeb824b1-6e9b-476d-80be-754935c650ef.png)

I have raised the severity higher than the other bugs that did not update the UI as I believe users add wrongly formatted dates often.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: garylow2001/ped#3

**Comment by ChongWeiJie29** [comment]
Similar to #172
